run:
  timeout: 5m
  exclude-dirs:
    - vendor
    - examples
  skip-files:
    - '^.+test\.go$'
linters:
  enable:
    - errcheck
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  gocyclo:
    min-complexity: 20


